# permissions for end users to view kubesondes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubesonde-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubesonde
    app.kubernetes.io/part-of: kubesonde
    app.kubernetes.io/managed-by: kustomize
  name: kubesonde-viewer-role
rules:
- apiGroups:
  - security.kubesonde.io
  resources:
  - kubesondes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.kubesonde.io
  resources:
  - kubesondes/status
  verbs:
  - get
