name: Deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/**

jobs:
  prepare:
    uses: jackap/kubesonde/.github/workflows/frontend_base.yaml@main

  deploy:
    runs-on: ubuntu-latest
    needs:
      - prepare

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=./build --prod
