name: Build and test CRD

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Build
        working-directory: crd
        run: make build

      - name: Test
        working-directory: crd
        run: make test 

    
      - name: Run gosec 
        working-directory: crd
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          $(go env GOPATH)/bin/gosec -exclude-dir=vendor ./...
          $(go env GOPATH)/bin/gosec -fmt sarif -exclude-dir=vendor -out gosec.sarif ./...

      - name: Upload SARIF file
        if: github.ref == 'refs/heads/main'
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e  # v4
        with:
          sarif_file: gosec.sarif

      - name: Add git safe.directory for container
        run: |
          mkdir -p /home/runner/work/_temp/_github_home
          printf "[safe]\ndirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

      - name: Install govulncheck
        working-directory: crd
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        working-directory: crd
        run: $(go env GOPATH)/bin/govulncheck ./...