name: Build and Test controller

on:
  push:
    branches:
      - dev
    paths:
      - crd/**
      - .github/**
  pull_request:
    branches:
      - "**"
    paths:
      - crd/**
      - .github/**

jobs:
  prepare:
    uses: kubesonde/kubesonde/.github/workflows/go_base.yaml@main
